name: frida-versions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: dep
        run: |
          pip install johnnydep
          sudo apt-get update
          sudo apt-get install jq curl -y
      - name: run
        run: |
          bash frida-versions.sh
